# Generated by Django 4.2 on 2023-05-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Например: +996 (555) 55 55 55', max_length=200, verbose_name='Телефонный номер'),
        ),
    ]
