# Generated by Django 4.2 on 2023-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Такси', 'verbose_name_plural': 'Таски'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(upload_to='todo_image/', verbose_name='Фотография'),
        ),
    ]
